import type { Teacher, ActivityLog, DepartmentStats, SubjectStats } from "./types"

export const subjects = [
  "Mathematics",
  "English",
  "Physics",
  "Chemistry",
  "Biology",
  "History",
  "Geography",
  "Computer Science",
  "Art",
  "Music",
  "Physical Education",
  "Economics",
]

export const classes = [
  "Grade 9A",
  "Grade 9B",
  "Grade 10A",
  "Grade 10B",
  "Grade 11A",
  "Grade 11B",
  "Grade 12A",
  "Grade 12B",
]

export const departments = ["Science", "Mathematics", "Languages", "Arts", "Social Studies", "Physical Education"]

// export const mockTeachers: Teacher[] = [
//   {
//     id: "1",
//     name: "Sarah Johnson",
//     email: "sarah.johnson@school.edu",
//     phone: "+1 (555) 123-4567",
//     gender: "female",
//     subjects: ["Mathematics", "Physics"],
//     classes: ["Grade 10A", "Grade 11B"],
//     status: "active",
//     dateJoined: "2023-08-15",
//     department: "Science",
//     avatar: "/female-teacher-portrait.png",
//   },
//   {
//     id: "2",
//     name: "Michael Chen",
//     email: "michael.chen@school.edu",
//     phone: "+1 (555) 234-5678",
//     gender: "male",
//     subjects: ["English", "History"],
//     classes: ["Grade 9A", "Grade 12A"],
//     status: "active",
//     dateJoined: "2022-01-10",
//     department: "Languages",
//     avatar: "/male-teacher-portrait-asian.jpg",
//   },
//   {
//     id: "3",
//     name: "Emily Rodriguez",
//     email: "emily.rodriguez@school.edu",
//     phone: "+1 (555) 345-6789",
//     gender: "female",
//     subjects: ["Biology", "Chemistry"],
//     classes: ["Grade 10B", "Grade 11A"],
//     status: "active",
//     dateJoined: "2024-11-20",
//     department: "Science",
//     avatar: "/female-teacher-portrait-latina.jpg",
//   },
//   {
//     id: "4",
//     name: "David Williams",
//     email: "david.williams@school.edu",
//     phone: "+1 (555) 456-7890",
//     gender: "male",
//     subjects: ["Computer Science"],
//     classes: ["Grade 11A", "Grade 12B"],
//     status: "inactive",
//     dateJoined: "2021-09-05",
//     department: "Science",
//     avatar: "/male-teacher-portrait-glasses.jpg",
//   },
//   {
//     id: "5",
//     name: "Lisa Thompson",
//     email: "lisa.thompson@school.edu",
//     phone: "+1 (555) 567-8901",
//     gender: "female",
//     subjects: ["Art", "Music"],
//     classes: ["Grade 9B", "Grade 10A"],
//     status: "active",
//     dateJoined: "2023-03-22",
//     department: "Arts",
//     avatar: "/female-teacher-portrait-creative.jpg",
//   },
//   {
//     id: "6",
//     name: "James Anderson",
//     email: "james.anderson@school.edu",
//     phone: "+1 (555) 678-9012",
//     gender: "male",
//     subjects: ["Physical Education"],
//     classes: ["Grade 9A", "Grade 9B", "Grade 10A", "Grade 10B"],
//     status: "active",
//     dateJoined: "2020-08-01",
//     department: "Physical Education",
//     avatar: "/male-athletic-teacher.jpg",
//   },
//   {
//     id: "7",
//     name: "Maria Garcia",
//     email: "maria.garcia@school.edu",
//     phone: "+1 (555) 789-0123",
//     gender: "female",
//     subjects: ["Geography", "Economics"],
//     classes: ["Grade 11B", "Grade 12A"],
//     status: "active",
//     dateJoined: "2024-12-01",
//     department: "Social Studies",
//     avatar: "/female-teacher-portrait-professional.jpg",
//   },
//   {
//     id: "8",
//     name: "Robert Brown",
//     email: "robert.brown@school.edu",
//     phone: "+1 (555) 890-1234",
//     gender: "male",
//     subjects: ["Mathematics"],
//     classes: ["Grade 12A", "Grade 12B"],
//     status: "inactive",
//     dateJoined: "2019-06-15",
//     department: "Mathematics",
//     avatar: "/male-senior-teacher.jpg",
//   },
// ]

export const mockActivities: ActivityLog[] = [
  {
    id: "1",
    action: "New teacher added",
    teacherName: "Maria Garcia",
    timestamp: "2024-12-01T09:30:00",
    type: "added",
  },
  {
    id: "2",
    action: "Profile updated",
    teacherName: "Sarah Johnson",
    timestamp: "2024-11-28T14:15:00",
    type: "updated",
  },
  {
    id: "3",
    action: "Status changed to inactive",
    teacherName: "Robert Brown",
    timestamp: "2024-11-25T11:00:00",
    type: "status_change",
  },
  {
    id: "4",
    action: "Assigned to Grade 11A",
    teacherName: "Emily Rodriguez",
    timestamp: "2024-11-20T16:45:00",
    type: "assignment",
  },
  {
    id: "5",
    action: "New teacher added",
    teacherName: "Emily Rodriguez",
    timestamp: "2024-11-20T10:00:00",
    type: "added",
  },
]

// export const departmentStats: DepartmentStats[] = [
//   { name: "Science", count: 12 },
//   { name: "Mathematics", count: 8 },
//   { name: "Languages", count: 10 },
//   { name: "Arts", count: 6 },
//   { name: "Social Studies", count: 5 },
//   { name: "Physical Education", count: 4 },
// ]

// export const subjectStats: SubjectStats[] = [
//   { name: "Mathematics", count: 8 },
//   { name: "English", count: 7 },
//   { name: "Physics", count: 5 },
//   { name: "Chemistry", count: 5 },
//   { name: "Biology", count: 4 },
//   { name: "History", count: 4 },
//   { name: "Geography", count: 3 },
//   { name: "Computer Science", count: 6 },
//   { name: "Art", count: 3 },
//   { name: "Music", count: 2 },
//   { name: "Physical Education", count: 4 },
//   { name: "Economics", count: 3 },
// ]
