import { School, StudentRowProps, Teacher } from "./types";

// export const  OverviewSchoolTableHeader = ["Id", "SchoolName", "AdminName","Email","Region","DateJoined","Status","Action"]


// OVERVIEW PAGE SCHOOL TABLE
export const OverviewSchoolTable: School[]= [
    {
        id:1,
        schoolName: "Law Acadamy",
        adminName: "Lawson Samson",
        email: "LawAca@school.edu",
        region: "Sunyani",
        dateJoined: "2023-09-15",
        status: "Active",
      
    },
    {
        id:2,
        schoolName: "Gideon Education Complex",
        adminName: "Gideon Asare",
        email: "MJ@school.edu",
        region: "Kumasi",
        dateJoined: "2021-03-14",
        status: "Pending",
       
    },
    {
        id:3,
        schoolName: "Tutu School",
        adminName: "Tutu Asare",
        email: "tutu@school.edu",
        region: "Accra",
        dateJoined: "2025-01-10",
        status: "Active",
      
    },
    {
        id:4,
        schoolName: "Solomon Acadamy",
        adminName: "Solomon",
        email: "solo@school.edu",
        region: "Tamale",
        dateJoined: "2018-10-18",
        status: "Suspended",
  
    },
    {
        id:5,
        schoolName: "Samson brain",
        adminName: "Samson Lawson",
        email: "sam@school.edu",
        region: "Bono",
        dateJoined: "2022-03-45",
        status: "Pending",
    },
    {
        id:6,
        schoolName: "Kumasi Anglican",
        adminName: "Adonko Oppong",
        email: "Kass@school.edu",
        region: "Kumasi",
        dateJoined: "2020-11-21",
        status: "Active",
    }
];

                          
                          
  // TEACHERS PAGE TABLE
  export const TeachersTable: Teacher[] = [
    {
      // avatar: "/teacher-img/student-emma.jpg",
      id: "1",
      name: "Sarah Johnson",
      email: "sarah.johnson@school.edu",
      phone: "+1 (555) 123-4567",
      gender: "female",
      subjects: ["Mathematics", "Physics"],
      classes: ["Grade 10A", "Grade 11B"],
      status: "active",
      dateJoined: "2023-08-15",
      department: "Science",
    },
    {
      // avatar: "/teacher-img/2.jpg",
      id: "2",
      name: "Michael Chen",
      email: "michael.chen@school.edu",
      phone: "+1 (555) 234-5678",
      gender: "male",
      subjects: ["English", "History"],
      classes: ["Grade 9A", "Grade 12A"],
      status: "active",
      dateJoined: "2022-01-10",
      department: "Languages",
    },
    {
      // avatar: "/purple-dices.jpg",
      id: "3",
      name: "Emily Rodriguez",
      email: "emily.rodriguez@school.edu",
      phone: "+1 (555) 345-6789",
      gender: "female",
      subjects: ["Biology", "Chemistry"],
      classes: ["Grade 10B", "Grade 11A"],
      status: "active",
      dateJoined: "2024-11-20",
      department: "Science",
    },
    {
      // avatar: "1.jpg",
      id: "4",
      name: "David Williams",
      email: "david.williams@school.edu",
      phone: "+1 (555) 456-7890",
      gender: "male",
      subjects: ["Computer Science"],
      classes: ["Grade 11A", "Grade 12B"],
      status: "inactive",
      dateJoined: "2021-09-05",
      department: "Science",
      },
    {
      id: "5",
      name: "Lisa Thompson",
      email: "lisa.thompson@school.edu",
      phone: "+1 (555) 567-8901",
      gender: "female",
      subjects: ["Art", "Music"],
      classes: ["Grade 9B", "Grade 10A"],
      status: "active",
      dateJoined: "2023-03-22",
      department: "Arts",
      // avatar: "/female-teacher-portrait-creative.jpg",
    },
    {
      id: "6",
      name: "James Anderson",
      email: "james.anderson@school.edu",
      phone: "+1 (555) 678-9012",
      gender: "male",
      subjects: ["Physical Education"],
      classes: ["Grade 9A", "Grade 9B", "Grade 10A", "Grade 10B"],
      status: "active",
      dateJoined: "2020-08-01",
      department: "Physical Education",
      // avatar: "/male-athletic-teacher.jpg",
    },
    {
      id: "7",
      name: "Maria Garcia",
      email: "maria.garcia@school.edu",
      phone: "+1 (555) 789-0123",
      gender: "female",
      subjects: ["Geography", "Economics"],
      classes: ["Grade 11B", "Grade 12A"],
      status: "active",
      dateJoined: "2024-12-01",
      department: "Social Studies",
      // avatar: "/female-teacher-portrait-professional.jpg",
    },
    {
      id: "8",
      name: "Robert Brown",
      email: "robert.brown@school.edu",
      phone: "+1 (555) 890-1234",
      gender: "male",
      subjects: ["Mathematics"],
      classes: ["Grade 12A", "Grade 12B"],
      status: "inactive",
      dateJoined: "2019-06-15",
      department: "Mathematics",
      // avatar: "/male-senior-teacher.jpg",
    },
  ]

    // Mock data
  export const StudentTableDetails={
    StudentTableHeader:["Student", "Student-ID", "Class", "Status"],
    StudentTableData:[
      {
        id: "STU001",
        name: "Emma Wilson",
        email: "emma.wilson@school.edu",
        avatar: "/teacher-img/student-emma.jpg",
        class: "Grade 10A",
        // progress: 85,
        status: "active" as const,
        lastActive: "2 hours ago",
        avgScore: 88,
      },
      {
        id: "STU002",
        name: "Liam Martinez",
        email: "liam.martinez@school.edu",
        avatar: "/teacher-img/student-liam.jpg",
        class: "Grade 11B",
        // progress: 72,
        status: "active" as const,
        lastActive: "5 hours ago",
        avgScore: 76,
      },
      {
        id: "STU003",
        name: "Olivia Chen",
        email: "olivia.chen@school.edu",
        avatar: "/teacher-img/student-olivia.jpg",
        class: "Grade 10A",
        // progress: 94,
        status: "active" as const,
        lastActive: "1 hour ago",
        avgScore: 92,
      },
      {
        id: "STU004",
        name: "Noah Johnson",
        email: "noah.johnson@school.edu",
        avatar: "/teacher-img/student-noah.jpg",
        class: "Grade 12C",
        // progress: 45,
        status: "inactive" as const,
        lastActive: "3 days ago",
        avgScore: 58,
      },
      {
        id: "STU005",
        name: "Sophia Patel",
        email: "sophia.patel@school.edu",
        avatar: "/teacher-img/student-sophia.png",
        class: "Grade 11A",
        // progress: 0,
        status: "suspended" as const,
        lastActive: "1 week ago",
        avgScore: 42,
      },
      {
        id: "STU006",
        name: "Jackson Lee",
        email: "jackson.lee@school.edu",
        avatar: "/teacher-img/student-jackson.jpg",
        class: "Grade 10B",
        // progress: 88,
        status: "active" as const,
        lastActive: "30 mins ago",
        avgScore: 85,
      },
      {
        id: "STU007",
        name: "Ava Thompson",
        email: "ava.thompson@school.edu",
        avatar: "/teacher-img/student-ava.jpg",
        class: "Grade 12A",
        // progress: 91,
        status: "active" as const,
        lastActive: "1 hour ago",
        avgScore: 94,
      },
      {
        id: "STU008",
        name: "Ethan Brown",
        email: "ethan.brown@school.edu",
        avatar: "/teacher-img/student-ethan.jpg",
        class: "Grade 11C",
        // progress: 67,
        status: "active" as const,
        lastActive: "6 hours ago",
        avgScore: 71,
      }, 
    ]
  }


// export const StudentsTableData: StudentRowProps[] = [
//   {
//     id: "STU001",
//     name: "Emma Wilson",
//     email: "emma.wilson@school.edu",
//     avatar: "/student-emma.jpg",
//     class: "Grade 10A",
//     // progress: 85,
//     status: "active" as const,
//     lastActive: "2 hours ago",
//     avgScore: 88,
//   },
//   {
//     id: "STU002",
//     name: "Liam Martinez",
//     email: "liam.martinez@school.edu",
//     avatar: "/student-liam.jpg",
//     class: "Grade 11B",
//     // progress: 72,
//     status: "active" as const,
//     lastActive: "5 hours ago",
//     avgScore: 76,
//   },
//   {
//     id: "STU003",
//     name: "Olivia Chen",
//     email: "olivia.chen@school.edu",
//     avatar: "/student-olivia.jpg",
//     class: "Grade 10A",
//     // progress: 94,
//     status: "active" as const,
//     lastActive: "1 hour ago",
//     avgScore: 92,
//   },
//   {
//     id: "STU004",
//     name: "Noah Johnson",
//     email: "noah.johnson@school.edu",
//     avatar: "/student-noah.jpg",
//     class: "Grade 12C",
//     // progress: 45,
//     status: "inactive" as const,
//     lastActive: "3 days ago",
//     avgScore: 58,
//   },
//   {
//     id: "STU005",
//     name: "Sophia Patel",
//     email: "sophia.patel@school.edu",
//     avatar: "/student-sophia.png",
//     class: "Grade 11A",
//     // progress: 0,
//     status: "suspended" as const,
//     lastActive: "1 week ago",
//     avgScore: 42,
//   },
//   {
//     id: "STU006",
//     name: "Jackson Lee",
//     email: "jackson.lee@school.edu",
//     avatar: "/student-jackson.jpg",
//     class: "Grade 10B",
//     // progress: 88,
//     status: "active" as const,
//     lastActive: "30 mins ago",
//     avgScore: 85,
//   },
//   {
//     id: "STU007",
//     name: "Ava Thompson",
//     email: "ava.thompson@school.edu",
//     avatar: "/student-ava.jpg",
//     class: "Grade 12A",
//     // progress: 91,
//     status: "active" as const,
//     lastActive: "1 hour ago",
//     avgScore: 94,
//   },
//   {
//     id: "STU008",
//     name: "Ethan Brown",
//     email: "ethan.brown@school.edu",
//     avatar: "/student-ethan.jpg",
//     class: "Grade 11C",
//     // progress: 67,
//     status: "active" as const,
//     lastActive: "6 hours ago",
//     avgScore: 71,
//   },
// ];
                          
                          